// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw1_K3YE5UVgXN4s6wEFeZR6EiuEdnfmk',
    appId: '1:404781552195:web:c8f47647e6562e471dbaf6',
    messagingSenderId: '404781552195',
    projectId: 'arjuna-gym',
    authDomain: 'arjuna-gym.firebaseapp.com',
    storageBucket: 'arjuna-gym.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBNhYNW9_1KoXPRiOtSXDwC221utvGcWQ',
    appId: '1:404781552195:android:5b84bab0c82367b91dbaf6',
    messagingSenderId: '404781552195',
    projectId: 'arjuna-gym',
    storageBucket: 'arjuna-gym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuvw0psc9ijD3rNajTi4g6WC6XJKRVgbo',
    appId: '1:404781552195:ios:22aaddcba01cdfa61dbaf6',
    messagingSenderId: '404781552195',
    projectId: 'arjuna-gym',
    storageBucket: 'arjuna-gym.appspot.com',
    iosBundleId: 'com.example.attendanceGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuvw0psc9ijD3rNajTi4g6WC6XJKRVgbo',
    appId: '1:404781552195:ios:22aaddcba01cdfa61dbaf6',
    messagingSenderId: '404781552195',
    projectId: 'arjuna-gym',
    storageBucket: 'arjuna-gym.appspot.com',
    iosBundleId: 'com.example.attendanceGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw1_K3YE5UVgXN4s6wEFeZR6EiuEdnfmk',
    appId: '1:404781552195:web:0dd0ecb7a9b6a1a31dbaf6',
    messagingSenderId: '404781552195',
    projectId: 'arjuna-gym',
    authDomain: 'arjuna-gym.firebaseapp.com',
    storageBucket: 'arjuna-gym.appspot.com',
  );
}
